### ISSUE TITLE
Quick calibration with different calibration curves.

### ISSUE THREAD

**Issue by TCLamnidis** [poseidon-framework/poseidonR#24]
Currently `quickcalibrate()` will assume calibration should happen using the IntCal20 calibration curve, but the underlying package used for calibration seems to support other calibration curves.
It would be nice to add an option to `quickcalibrate` that allows a user to provide a string of a calibration curve to use, or a vector of curves, in (rare) cases where a package contains sufficiently different data that different curves might make sense. 

For example with a given dataset like
| ages | sds | curves |
|------|----|--------|
| 350 | 25 | intcal20 |
| 1500 | 50 | shcal20 |

```R
## Calibrate everything with intcal20
quickcalibrate(ages, sds, curve="intcal20")
## Or use shcal20 for the second row
quickcalibrate(ages, sds, curves)
```

Not sure how easy this is to implement, but it would be nice to give users a bit more flexibility.

**Comment by nevrome** [comment]
That wouldn't be difficult to implement. I can add that. But note that quickcalibrate has a very limited scope: Don't use it for general calibration.

**Comment by nevrome** [comment]
added in v0.5.0
